### PR TITLE
Airship v2

### PR DESCRIPTION
**Pull request by rjimenezda**
Featuring, so far:

### Styles
Revamp Customization (#568)

### Histogram / TIme series:
Design Review (#560)
Multiline Tooltip (#561) 
Categorical data support (#564)
Background data (#565)
Histogram Axis options (#567)

### Bindings
Rename to Bridge, add new features (#570)
Global Histogram Support (#573)
Add another Filter: Global Range Slider (#574)

### CODE REVIEW

**Comment by rjimenezda** [comment]
cc @mbforr @CartoDB/frontend-team 

I've released a v2.0.0-rc.0, under the prerelease tag. It's also on the CDN

The bridge is not published to npm still. I have to check out if it's going to work nicely with npm or not, but I'd like it to be. 

So if you want to try it out: https://libs.cartocdn.com/airship-bridge/v2.0.0-rc.0/asbridge.min.js

You can see two examples on this branch under the packages/bridge/examples folder.

**Comment by Captain-Oski** [comment]
Hi ! 

Do you have an idea if you are going to push components 2.0 to npm ?

It would be 🔥 !

Thank you so much !

**Comment by rjimenezda** [comment]
Hi @Captain-Oski , it was released around when this PR got merged: https://npmjs.com/package/@carto/airship-components, and as always you can also use the CDN as seen on our examples.

You can check out our blog post for more details:
https://carto.com/blog/airship-v2/

**Comment by Captain-Oski** [comment]
Thank you !

**Comment by Captain-Oski** [comment]
Note that **npm i @carto/airship-components** will install 1.0.3 I had to specify the @^2.0.0

**Comment by rjimenezda** [comment]
@Captain-Oski 

I tested a brand new repo, with no dependencies and it installed @carto/airship-components@2.0.5. 

If it's already a dependency for you project, and it's specified as ^1.0.0, it won't install 2 because of semver. I don't know if that was the case :)

**Comment by Captain-Oski** [comment]
Thank you. 
Is the bridge included in the latest realese on npm ?

**Comment by rjimenezda** [comment]
Yep, but it's a separate npm package: @carto/airship-bridge. It's also published on the cdn: https://libs.cartocdn.com/airship-bridge/v2/asbridge.min.js

**Comment by Captain-Oski** [comment]
Thank you, you solved it all ! 🚀

**Pull request merged**
