### PR TITLE
Remove height style within widgets

### PR DESCRIPTION
**Pull request by ivanmalagon**
`height: 100%` was causing widgets on FF to not render well, occupying too much space and rendering different from the rest of browsers.

### CODE REVIEW

**Comment by IagoLast** [comment]
The [responsive smoke test](http://localhost:5000/packages/components/src/components/as-stacked-bar-widget/responsive) doesn't work anymore.

I think we should research the cause of that bug before removing the height.

**Comment by rjimenezda** [comment]
This is a massive inconsistency between firefox and webkit, and I think firefox is the one that's doing it right. On webkit they do not have 100% height on the sidebar container.

If our histogram / stacked-bar are supposed to take 100% height, we have to surround them with something instead of using them as siblings.

**Comment by rjimenezda** [comment]
If we keep the current implementation (100% height), we should update all examples with such widgets on sidbars, and maybe add a comment somewhere.

**Comment by ivanmalagon** [comment]
Done in https://github.com/CartoDB/airship/pull/502

**Pull request closed without merging**
