### PR TITLE
Add basic colors

### PR DESCRIPTION
**Pull request by rubenmoya**
#75 Add basic colors
---

This PR adds the basic Airship color scheme with SASS and CSS variables and updates them in the documentation and elements.

It also adds `postcss-css-variables` which adds a fallback with static content to the rules using CSS variables.

I ended up using `Gulp` since it was a pain to handle the integration between `node-sass` and `postcss`

### CODE REVIEW

**Comment by rubenmoya** [comment]
We are defining the variables always in `packages/styles/src/core/core.scss`

**Comment by IagoLast** [comment]
I meant using the [fallback values] in `var`:

```css
background-color: var(--panels-bg-color, $color-primary);
```

**Comment by rubenmoya** [comment]
Yes, but as I said, we are declaring `--panels-bg-color` ourselves, so there is no way it's not defined

**Comment by rubenmoya** [comment]
Nevermind, we need to add it because of the PostCSS plugin, since the variables are defined in core, and it's not available in the standalone components

**Comment by IagoLast** [comment]
> Yes, but as I said, we are declaring --panels-bg-color ourselves, so there is no way it's not defined

an user could f^*ck the styles overriding the variables with javascript :trollface: 

> Nevermind, we need to add it because of the PostCSS plugin, since the variables are defined in core, and it's not available in the standalone

I knew we did it for something!
:trollface:

**Pull request merged**
