### PR TITLE
Add basic tables

### PR DESCRIPTION
**Pull request by IagoLast**
#43 
---

### CODE REVIEW

**Comment by rubenmoya** [comment]
I think the green color in rows is because of `tr:hover` not becuase of `tr:even`

**Comment by IagoLast** [comment]
I think `:hover` is slightly darker

**Comment by rubenmoya** [comment]
There are two `:hover` effects, one for the `tr` and one for the `td`, both of them using opacity to get that effect (the cell being darker than the row), but the green color should be used only in hover effects, not in even rows

**Comment by IagoLast** [comment]
@rubenmoya fixed :)

**Comment by rubenmoya** [comment]
👍

**Pull request merged**
